# secrets.tf
# Two things happen here:
# 1. A random 16-char password is generated by Terraform (never written to any file).
# 2. That password is stored in AWS Secrets Manager alongside the full DB connection
#    info as a JSON blob — the same format the Lambda rotation function expects.
# The EC2 instance and Lambda both read this secret at runtime via IAM role — no
# hardcoded credentials anywhere in the codebase.

resource "random_password" "rds" {
  length           = 16
  special          = true
  # Exclude characters that break PostgreSQL connection strings
  override_special = "!#$%&*()-_=+[]{}?"
}

resource "aws_secretsmanager_secret" "rds" {
  name        = "vaultops/rds-password"
  description = "VaultOps RDS credentials — auto-rotated by Lambda"

  # Secrets Manager charges $0.40/secret/month after the 30-day free trial.
  # For a 3-week project this stays free. Set recovery window to 0 so
  # terraform destroy can immediately delete it (no 7-30 day recovery period).
  recovery_window_in_days = 0

  tags = {
    Name = "vaultops-rds-secret"
  }
}

# Store the actual secret value as JSON.
# This exact JSON structure is what the Lambda rotation function (Day 6)
# expects — host, port, dbname, username, password all in one place.
resource "aws_secretsmanager_secret_version" "rds" {
  secret_id = aws_secretsmanager_secret.rds.id

  secret_string = jsonencode({
    host     = aws_db_instance.vaultops.address
    port     = 5432
    dbname   = "vaultops"
    username = "vaultops_user"
    password = random_password.rds.result
  })
}

output "secret_arn" {
  description = "ARN of the RDS secret — used in Lambda and EC2 IAM policies"
  value       = aws_secretsmanager_secret.rds.arn
}
